<p style="text-align: right;"> Name : Duaa-e-Nadeem (SP24-PCS-005) </p>

## ASSIGNMENT 1

### Task 1: Lists, Dictionaries, Tuples

#### 1.1. Creaye a list: nums = [3, 5, 7, 8, 12], make another list named ‘cubes’ and append the cubes of the given list ‘nums’ in this list and print it.

In [1]:
nums = [3, 5, 7, 8, 12]
cubes = []

for num in nums:
    # Appending the cube of each number to the cubes list
    cubes.append(num ** 3)  

print("Cubes of the list nums:", cubes)

Cubes of the list nums: [27, 125, 343, 512, 1728]


#### 1.2. Create an empty dictionary: dict = {}, add the following data to the dictionary: ‘parrot’: 2, ‘goat’: 4, ‘spider’: 8, ‘crab’: 10 as key value pairs.

In [2]:
dict = {}
dict['parrot'] = 2
dict['goat'] = 4
dict['spider'] = 8
dict['crab'] = 10

print("Dictionary with animals and their number of legs:", dict)


Dictionary with animals and their number of legs: {'parrot': 2, 'goat': 4, 'spider': 8, 'crab': 10}


#### 1.3. Use the ‘items’ method to loop over the dictionary (dict) and print the animals and their corresponding legs. Sum the legs of each animal, and print the total at the end.

In [3]:
total_legs = 0

for animal in dict:  # Looping directly over the keys (animals)
    legs = dict[animal]  # Accessing the value (legs) using the key
    print(f"The {animal} has {legs} legs.")
    total_legs += legs

print("Total number of legs:", total_legs)

The parrot has 2 legs.
The goat has 4 legs.
The spider has 8 legs.
The crab has 10 legs.
Total number of legs: 24


#### 1.4. Create a tuple: A = (3, 9, 4, [5, 6]), change the value in the list from ‘5’ to ‘8’.

In [8]:
A = (3, 9, 4, [5, 6])
A[3][0] = 8  # Changing 5 to 8 in the list
print("Changed tuple A:", A)


Changed tuple A: (3, 9, 4, [8, 6])


#### 1.5. Delete the tuple A.

In [9]:
del A

#### 1.6. Create another tuple: B = (‘a’, ‘p’, ‘p’, ‘l’, ‘e’), print the number of occurrences of ‘p’ in the tuple.

In [10]:
B = ('a', 'p', 'p', 'l', 'e')
print("Occurrences of 'p' in tuple B:", B.count('p'))

Occurrences of 'p' in tuple B: 2


#### 1.7. Print the index of ‘l’ in the tuple.

In [11]:
print("Index of 'l' in tuple B:", B.index('l'))

Index of 'l' in tuple B: 3


### Task 2: Numpy

#### Use built-in functions of numpy library to complete this task.
#### List of functions available here (https://numpy.org/doc/1.19/genindex.html)
#### A = 
####      1   2      3      4
####       5    6     7       8
####       9    10  11     12
#### z = np.array([1, 0, 1])

#### 2.1 Convert matrix A into numpy array

In [12]:
import numpy as np

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

print("Matrix A as numpy array:")
print(A)

Matrix A as numpy array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### 2.2 Use slicing to pull out the subarray consisting of the first 2 rows and columns 1 and 2. Store it in b which is a numpy array of shape (2, 2).

In [13]:
b = A[:2, :2]

print("Subarray b (first 2 rows and columns 1 and 2):")
print(b)

Subarray b (first 2 rows and columns 1 and 2):
[[1 2]
 [5 6]]


#### 2.3 Create an empty matrix ‘C’ with the same shape as ‘A’.

In [14]:
C = np.empty_like(A)
print("Empty matrix C with the same shape as A:")
print(C)

Empty matrix C with the same shape as A:
[[2 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


#### 2.4 Add the vector z to each column of the matrix ‘A’ with an explicit loop and store it in ‘C’. Create the following:
#### X = np.array([[1,2],[3,4]])
#### Y = np.array([[5,6],[7,8]])
#### v = np.array([9,10])

In [15]:
z = np.array([1, 0, 1])

for i in range(A.shape[1]):  
    C[:, i] = A[:, i] + z  # Add vector z to each column of A

print("Matrix C after adding vector z to each column of A:")
print(C)

Matrix C after adding vector z to each column of A:
[[ 2  3  4  5]
 [ 5  6  7  8]
 [10 11 12 13]]


#### 2.5 Add and print the matrices X and Y.

In [17]:
X = np.array([[1, 2],
              [3, 4]])
Y = np.array([[5, 6],
              [7, 8]])

sum_XY = np.add(X, Y)
print("\nSum of X and Y:\n", sum_XY)


Sum of X and Y:
 [[ 6  8]
 [10 12]]


#### 2.6 Multiply and print the matrices X and Y.

In [18]:
mul_XY = X * Y 
print("\n multiplication of X and Y:")
print(mul_XY)


 multiplication of X and Y:
[[ 5 12]
 [21 32]]


#### 2.7 Compute and print the element wise square root of matrix Y.

In [19]:
sqrt_Y = np.sqrt(Y) 
print("\n Element-wise square root of matrix Y:")
print(sqrt_Y)


Element-wise square root of matrix Y:
[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


#### 2.8 Compute and print the dot product of the matrix X and vector v. 

In [20]:
v = np.array([9, 10])

dot_product = np.dot(X, v) 
print("\n Dot product of matrix X and vector v:")
print(dot_product)


 Dot product of matrix X and vector v:
[29 67]


#### 2.9 Compute and print the sum of each column of X.

In [21]:
column_sum_X = np.sum(X, axis=0) 
print("\n Sum of each column of matrix X:")
print(column_sum_X)


 Sum of each column of matrix X:
[4 6]


### Task 3: Functions and Loops
#### 3.1 Create a function ‘Compute’ that takes two arguments, distance and time, and use it to calculate velocity. 

In [23]:
def Compute(distance, time):
    if time == 0:
        return "Time cannot be zero!"  
    velocity = distance / time  # Velocity = Distance / Time
    return velocity

#### 3.2 Make a list named ‘even_num’ that contains all even numbers up till 12. Create a function ‘mult’ that takes the list ‘even_num’ as an argument and calculates the products of all entries using a for loop.

In [25]:
even_num = [2, 4, 6, 8, 10, 12]  
def mult(numbers):
    product = 1  
    for num in numbers:
        product *= num  
    return product

### Task 4: Pandas
### Create a Pandas dataframe named ‘pd’ that contains 5 rows and 4 columns, similar to the one given below:
### C1 C2 C3 C4
### 1 6 7 7
### 2 7 9 5
### 3 5 8 2
### 5 4 6 8
### 5 8 5 8
#### 4.1 Print only the first two rows of the dataframe.

In [26]:
import pandas as pd
# Create the dataframe
data = {
    'C1': [1, 2, 3, 5, 5],
    'C2': [6, 7, 5, 4, 8],
    'C3': [7, 9, 8, 6, 5],
    'C4': [7, 5, 2, 8, 8]
}
df = pd.DataFrame(data)
print("Initial DataFrame:")
print(df)

print("\nFirst two rows:")
print(df.head(2))


Initial DataFrame:
   C1  C2  C3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8

First two rows:
   C1  C2  C3  C4
0   1   6   7   7
1   2   7   9   5


#### 4.2 Print the second column.

In [28]:
print("Second column (C2):")
print(df['C2']) 

Second column (C2):
0    6
1    7
2    5
3    4
4    8
Name: C2, dtype: int64


#### 4.3 Change the name of the third column from ‘C3’ to ‘B3’.

In [30]:
df.rename(columns={'C3': 'B3'}, inplace=True)
print("DataFrame after renaming column C3 to B3:")
print(df)

DataFrame after renaming column C3 to B3:
   C1  C2  B3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8


#### 4.4 Add a new column to the dataframe and name it ‘Sum’.

In [31]:
df['Sum'] = 0 
print("DataFrame after adding 'Sum' column:")
print(df)

DataFrame after adding 'Sum' column:
   C1  C2  B3  C4  Sum
0   1   6   7   7    0
1   2   7   9   5    0
2   3   5   8   2    0
3   5   4   6   8    0
4   5   8   5   8    0


#### 4.5 Sum the entries of each row and add the result in the column ‘Sum’.

In [32]:
df['Sum'] = df.sum(axis=1) 
print("DataFrame after summing rows into 'Sum' column:")
print(df)

DataFrame after summing rows into 'Sum' column:
   C1  C2  B3  C4  Sum
0   1   6   7   7   21
1   2   7   9   5   23
2   3   5   8   2   18
3   5   4   6   8   23
4   5   8   5   8   26


#### 4.6 Read CSV file named ‘hello_sample.csv’ (the file is available in the class Google Drive shared folder) into a Pandas dataframe.

In [33]:
csv_df = pd.read_csv('hello_sample.csv')

#### 4.7 Print complete dataframe.

In [34]:
print("Complete dataframe from CSV:")
print(csv_df)

Complete dataframe from CSV:
    Gender  F_Color     B_Month  Weight
0     Male    Black       March      77
1     Male      Red       March      72
2     Male    Black     October      53
3   Female     Blue    February      63
4     Male    black    October       80
5   Female    Black    december      97
6     Male   Orange      August      60
7   Female      Red   September      59
8     Male     Blue        July      60
9     Male     Blue         May      58
10  Female      Red    October       60
11    Male    Black   September      65
12    Male    Green    December      85
13    Male    Black       April      72
14    Male    Green    January       90
15    Male   Yellow   November       90
16    Male    Black      August      54
17    Male    Black     January      82
18    Male  Mustard   December       60
19  Female    Black    October       76
20    Male    Black   February       67
21    Male   Yellow       April      74
22    Male      Red  September       66


#### 4.8 Print only bottom 2 records of the dataframe.

In [35]:
print("Bottom two records of the dataframe:")
print(csv_df.tail(2))

Bottom two records of the dataframe:
   Gender F_Color     B_Month  Weight
21   Male  Yellow       April      74
22   Male     Red  September       66


#### 4.9 Print information about the dataframe.

In [36]:
print("Information about the dataframe:")
print(csv_df.info()) 

Information about the dataframe:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Gender   23 non-null     object
 1   F_Color  23 non-null     object
 2   B_Month  23 non-null     object
 3   Weight   23 non-null     int64 
dtypes: int64(1), object(3)
memory usage: 868.0+ bytes
None


#### 4.10 Print shape (rows x columns) of the dataframe.

In [37]:
print("Shape of the dataframe (rows x columns):")
print(csv_df.shape)

Shape of the dataframe (rows x columns):
(23, 4)


#### 4.11 Sort the data of the dataFrame using column ‘Weight’.

In [39]:
if 'Weight' in csv_df.columns: 
    sorted_df = csv_df.sort_values(by='Weight')
    print("Data sorted by 'Weight':")
    print(sorted_df)
else:
    print("\n'Weight' column not found in the dataframe.")


Data sorted by 'Weight':
    Gender  F_Color     B_Month  Weight
2     Male    Black     October      53
16    Male    Black      August      54
9     Male     Blue         May      58
7   Female      Red   September      59
18    Male  Mustard   December       60
10  Female      Red    October       60
6     Male   Orange      August      60
8     Male     Blue        July      60
3   Female     Blue    February      63
11    Male    Black   September      65
22    Male      Red  September       66
20    Male    Black   February       67
13    Male    Black       April      72
1     Male      Red       March      72
21    Male   Yellow       April      74
19  Female    Black    October       76
0     Male    Black       March      77
4     Male    black    October       80
17    Male    Black     January      82
12    Male    Green    December      85
14    Male    Green    January       90
15    Male   Yellow   November       90
5   Female    Black    december      97


#### 4.12 Use isnull() and dropna() methods of the Pandas dataframe and see if they produce any changes.

In [40]:
print("Checking for missing values using isnull():")
print(csv_df.isnull()) 

print("\nDropping rows with missing values using dropna():")
clean_df = csv_df.dropna() 
print(clean_df)

Checking for missing values using isnull():
    Gender  F_Color  B_Month  Weight
0    False    False    False   False
1    False    False    False   False
2    False    False    False   False
3    False    False    False   False
4    False    False    False   False
5    False    False    False   False
6    False    False    False   False
7    False    False    False   False
8    False    False    False   False
9    False    False    False   False
10   False    False    False   False
11   False    False    False   False
12   False    False    False   False
13   False    False    False   False
14   False    False    False   False
15   False    False    False   False
16   False    False    False   False
17   False    False    False   False
18   False    False    False   False
19   False    False    False   False
20   False    False    False   False
21   False    False    False   False
22   False    False    False   False

Dropping rows with missing values using dropna():
    Gender  F_Col